# -*- coding: utf-8 -*-
"""data_overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2qinigez4hGvfkaviQ0TxwKdkZQ_QUh
"""

import pandas as pd
import plotly.express as px
import streamlit as st

def app():
    # Page title
    st.header("📊 India Air Quality Dataset Overview")

    # --- Sidebar About Section ---
    st.sidebar.title("👀 About This App")
    st.sidebar.markdown("""
    This app provides:

    - 📊 Overview of India's air quality dataset
    - 🧹 Data preprocessing & cleaning tools
    - 🎨 Data visualizations for pollutants
    - 🤖 Model building and AQI predictions

    Explore air pollution trends across 26 cities (2015–2020).
    """)

    # --- Main Page Content ---
    st.markdown("""
    ### About the Dataset
    India Air Quality Dataset contains a total of 29,531 rows and 17 columns, covering 26 unique cities over the years 2015–2020.
    It represents daily values of different air pollutants, including AQI values and AQI categories.

    ---
    This page includes:

    - **Raw Data**
    - **Dimensional Structure**
    - **Column Name Description**
    - **Unique City List**
    """)

    # City coordinates
    city_coords = {
        "Mumbai": (19.0760, 72.8777),
        "Lucknow": (26.8467, 80.9462),
        "Aizawl": (23.7271, 92.7176),
        "Chennai": (13.0827, 80.2707),
        "Chandigarh": (30.7333, 76.7794),
        "Shillong": (25.5788, 91.8933),
        "Gurugram": (28.4595, 77.0266),
        "Bengaluru": (12.9716, 77.5946),
        "Jorapokhar": (23.7519, 86.4146),
        "Hyderabad": (17.3850, 78.4867),
        "Talcher": (20.9517, 85.2335),
        "Guwahati": (26.1445, 91.7362),
        "Delhi": (28.6139, 77.2090),
        "Patna": (25.5941, 85.1376),
        "Brajrajnagar": (21.8167, 83.9167),
        "Bhopal": (23.2599, 77.4126),
        "Amaravati": (16.5417, 80.5150),
        "Amritsar": (31.6340, 74.8723),
        "Kolkata": (22.5726, 88.3639),
        "Ernakulam": (9.9816, 76.2999),
        "Coimbatore": (11.0168, 76.9558),
        "Ahmedabad": (23.0225, 72.5714),
        "Jaipur": (26.9124, 75.7873),
        "Kochi": (9.9312, 76.2673),
        "Thiruvananthapuram": (8.5241, 76.9366),
        "Visakhapatnam": (17.6868, 83.2185),
    }

    # Convert to DataFrame for plotting
    df_cities = pd.DataFrame([{"City": city, "Latitude": lat, "Longitude": lon}
                              for city, (lat, lon) in city_coords.items()])

    # Create Plotly Scatter Map
    fig_map = px.scatter_geo(
        df_cities,
        lat="Latitude",
        lon="Longitude",
        text="City",
        scope="asia",
        projection="natural earth",
        title="India – Highlighted Air Quality Monitoring Cities"
    )
    fig_map.update_traces(marker=dict(size=10, color="red", symbol="circle"),
                          textposition="top center")
    fig_map.update_geos(fitbounds="locations", showcountries=True, countrycolor="black",
                        showland=True, landcolor="lightgray")
    st.plotly_chart(fig_map, use_container_width=True)

    # --- Load dataset ---
    df_dataset = pd.read_csv("cleaned_India_air_quality.csv")

    # Slider for dataset preview
    rows_to_show = st.slider("Select number of rows to preview", 5, 200, 10)

    st.subheader("📝 Preview of Dataset")
    st.dataframe(df_dataset.head(rows_to_show), use_container_width=True)

    st.subheader("📅 Dataset Shape")
    st.write(f"**Rows:** {df_dataset.shape[0]}  |  **Columns:** {df_dataset.shape[1]}")

    # --- Pollutants Overview ---
    st.subheader("🧪 Pollutants Overview")

    # Creating a dataframe for pollutants with their type
    df_pollutants = pd.DataFrame({
        "Pollutant": ["PM2.5", "PM10", "NO", "NO₂", "NOx", "NH₃", "SO₂", "CO", "O₃", "BTX"],
        "Type": ["Particulate", "Particulate", "Gas", "Gas", "Gas", "Gas", "Gas", "Gas", "Gas", "VOC"],
        "Harmfulness": [10, 7, 6, 8, 8, 5, 6, 6, 7, 9],  # Harmfulness score
        "Description": [
            "Fine particulate matter (most harmful)",
            "Coarse particulate matter",
            "Nitric oxide",
            "Nitrogen dioxide",
            "Total nitrogen oxides (NO + NO₂)",
            "Ammonia",
            "Sulfur dioxide",
            "Carbon monoxide",
            "Ozone",
            "Industrial VOC pollutants"
        ]
    })

    # Create the Sunburst chart with two levels of hierarchy
    fig_sunburst = px.sunburst(
        df_pollutants,
        path=["Type", "Pollutant"],  # Two levels: Type and Pollutant
        values="Harmfulness",  # Values represent Harmfulness score
        hover_data=["Description"],  # Display Description on hover
        color="Harmfulness",  # Color by Harmfulness for visual emphasis
        color_continuous_scale="Viridis",  # Color scale
        title="Pollutants Overview"
    )

    # Show the chart in Streamlit
    st.plotly_chart(fig_sunburst)

    # AQI Columns info
    st.subheader("📊 AQI Columns")
    st.markdown("""
    - **AQI** → Air Quality Index value
    - **AQI_Bucket** → Category such as:
        - Good
        - Satisfactory
        - Moderate
        - Poor
        - Very Poor
        - Severe
    """)

    # Unique cities dropdown
    st.subheader("🔽 Check Unique Cities 🏙️")
    cities = sorted(df_dataset['City'].dropna().unique())
    selected_cities = st.multiselect("Select one or more cities:", cities)

    if selected_cities:
        st.write("You selected:", selected_cities)
    else:
        st.write("No city selected yet.")