# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ulox1HHxTY9R7KHojKzlEXF56yY8loa
"""

import streamlit as st
import pandas as pd
import plotly.express as px

def app():
    # ---------------- Load Dataset ----------------
    df = pd.read_csv("cleaned_India_air_quality.csv")
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df['Year'] = df['Date'].dt.year

    st.title("Exploratory Data Analysis")

    # ---------------- Sidebar Options ----------------
    st.sidebar.title("EDA Options")
    show_pollutant_dist = st.sidebar.checkbox("Distribution of Pollutants")
    show_avg_by_city = st.sidebar.checkbox("Average Pollutant Levels by City")
    display_aqi_by_city = st.sidebar.checkbox('AQI by City')
    display_aqi_by_year = st.sidebar.checkbox('AQI by Year')
    display_aqi_by_bucket = st.sidebar.checkbox('AQI by AQI_Bucket')
    show_total_pollution = st.sidebar.checkbox("Total Pollution by City")
    show_aqi_by_season = st.sidebar.checkbox("Average AQI by Season")
    show_seasonal_pollutants = st.sidebar.checkbox("Seasonal Trend of Pollutants")

    # ---------------- Distribution of Pollutants ----------------
    if show_pollutant_dist:
        st.header("Distribution of Pollutants")
        numeric_cols = df.select_dtypes(include='number').columns.tolist()
        selected_column = st.selectbox("Select a pollutant:", numeric_cols, key="dist_pollutant")
        show_hist = st.checkbox(f"Show Histogram of {selected_column}", key="hist_checkbox")
        if show_hist:
            fig = px.histogram(df, x=selected_column, nbins=30,
                               title=f"Distribution of {selected_column}",
                               color_discrete_sequence=["skyblue"])
            fig.update_layout(xaxis_title=selected_column, yaxis_title="Frequency")
            st.plotly_chart(fig, use_container_width=True)

    # ---------------- Average Pollutant by City ----------------
    if show_avg_by_city:
        st.header("Average Pollutant Levels by City")
        pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
                      'Benzene', 'Toluene', 'Xylene', 'AQI']
        selected_avg_pollutant = st.selectbox("Choose a pollutant:", pollutants, key="avg_poll")
        show_avg = st.checkbox(f"Show average {selected_avg_pollutant} by City", key="avg_checkbox")
        if show_avg:
            City_avg = df.groupby('City')[selected_avg_pollutant].mean().sort_values(ascending=True).reset_index()
            fig = px.bar(City_avg, x=selected_avg_pollutant, y='City', orientation='h',
                         color=selected_avg_pollutant, color_continuous_scale='greens',
                         title=f"Average {selected_avg_pollutant} Levels by City")
            fig.update_layout(xaxis_title=f"Average {selected_avg_pollutant}",
                              yaxis_title="City", yaxis={'categoryorder':'total ascending'},
                              height=40*len(City_avg))
            st.plotly_chart(fig, use_container_width=True)



    # ---------------- Total Pollution & Most Polluted City ----------------
    if show_total_pollution:
        st.subheader("Total Pollution Score per City")
        pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx','NH3','CO', 'SO2', 'O3',
                      'Benzene', 'Toluene', 'Xylene']
        city_avg = df.groupby('City')[pollutants].mean()
        city_avg['Total_Pollution'] = city_avg.sum(axis=1)
        most_polluted_city = city_avg['Total_Pollution'].idxmax()
        most_pollution_value = city_avg.loc[most_polluted_city, 'Total_Pollution']
        st.markdown(f"**Most polluted city:** {most_polluted_city} - {most_pollution_value:.2f}")
        fig = px.bar(city_avg.reset_index(), x='City', y='Total_Pollution',
                     title='Total Pollution Score by City', color='Total_Pollution',
                     color_continuous_scale='Reds')
        fig.update_traces(marker_color=['darkred' if city==most_polluted_city else 'orange'
                                        for city in city_avg.index])
        st.plotly_chart(fig, use_container_width=True)

    # ---------------- AQI by City ----------------
    if display_aqi_by_city:
        st.subheader("AQI by City")
        selected_city_aqi = st.selectbox('Select a city', df['City'].unique(), key='aqi_city')
        city_data = df[df['City'] == selected_city_aqi]
        city_avg = city_data.groupby('Year')['AQI'].mean().reset_index()
        fig_aqi_city = px.bar(city_avg, x='Year', y='AQI', title=f'Average AQI Trend for {selected_city_aqi}',
                              color='AQI', color_continuous_scale='reds')
        fig_aqi_city.update_layout(yaxis_title='Average AQI')
        st.plotly_chart(fig_aqi_city, use_container_width=True)

    # ---------------- AQI by Year ----------------
    if display_aqi_by_year:
        st.subheader("AQI by Year")
        selected_year = st.selectbox('Select a year', sorted(df['Year'].dropna().unique()), key='aqi_year')
        year_data = df[df['Year'] == selected_year]
        city_avg = year_data.groupby('City')['AQI'].mean().reset_index()
        fig_aqi_year = px.bar(city_avg, x='City', y='AQI',
                              title=f'Average AQI by City in {selected_year}',
                              color='AQI', color_continuous_scale='viridis')
        fig_aqi_year.update_layout(yaxis_title='Average AQI', xaxis_title='City')
        st.plotly_chart(fig_aqi_year, use_container_width=True)

    # ---------------- AQI by Bucket ----------------
    if display_aqi_by_bucket:
        st.subheader("AQI by Bucket")
        bucket_counts = df['AQI_Bucket'].value_counts().reset_index()
        bucket_counts.columns = ['AQI_Bucket', 'Count']
        fig_aqi_bucket = px.bar(bucket_counts, x='AQI_Bucket', y='Count',
                                title='Distribution of AQI Buckets', color='Count',
                                color_continuous_scale='magma')
        st.plotly_chart(fig_aqi_bucket, use_container_width=True)



    # ---------------- Average AQI by Season ----------------
    if show_aqi_by_season:
        st.subheader("Average AQI by Season")
        season_aqi = df.groupby('season')['AQI'].mean().reset_index()
        most_polluted_season = season_aqi.loc[season_aqi['AQI'].idxmax()]
        top_season = most_polluted_season['season']
        fig = px.bar(season_aqi, x='season', y='AQI', color='AQI',
                     color_continuous_scale='Reds', title='Average AQI by Season')
        fig.update_traces(marker_color=['darkred' if season==top_season else 'orange'
                                        for season in season_aqi['season']])
        st.plotly_chart(fig, use_container_width=True)
        st.markdown(f"**Most polluted season:** {top_season} with AQI {most_polluted_season['AQI']:.2f}")

    # ---------------- Seasonal Trend of Pollutants ----------------
    if show_seasonal_pollutants:
        st.subheader("Seasonal Trend of Pollutants")
        pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx','NH3','CO', 'SO2', 'O3',
                      'Benzene', 'Toluene', 'Xylene']
        season_avg = df.groupby('season')[pollutants].mean().reset_index()
        season_long = season_avg.melt(id_vars='season', value_vars=pollutants,
                                      var_name='pollutant', value_name='Concentration')
        fig = px.bar(season_long, x='season', y='Concentration', color='pollutant',
                     barmode='group', title='Seasonal Trend of Pollutants')
        st.plotly_chart(fig, use_container_width=True)
        st.markdown("This chart shows how the concentration of each pollutant varies across seasons.")