# -*- coding: utf-8 -*-
"""model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZkWywUjS203bQPcur_l2RzqfifV-E0d
"""

import streamlit as st
import pandas as pd
import joblib


def app():
    st.title("AQI Prediction")

    st.write("Predict AQI value or AQI category using trained models.")

    # -----------------------------
    # Load models
    # -----------------------------
    try:
        reg_model = joblib.load("models/aqi_regression.pkl")
        cls_model = joblib.load("models/aqi_classification.pkl")
        st.success("Models loaded successfully")
    except:
        st.error("Model files not found. Train and save models first.")
        return

    st.divider()

    # -----------------------------
    # User input (simple)
    # -----------------------------
    st.subheader("Enter pollutant values")

    pm25 = st.number_input("PM2.5", value=50.0)
    pm10 = st.number_input("PM10", value=80.0)
    no2 = st.number_input("NO2", value=30.0)
    so2 = st.number_input("SO2", value=10.0)
    co = st.number_input("CO", value=0.8)
    o3 = st.number_input("O3", value=20.0)

    st.subheader("Date information")
    date = st.date_input("Select date")

    # Time features (must match training)
    year = date.year
    month = date.month
    day_of_week = date.weekday()

    # Optional categorical input
    city = st.text_input("City", value="Delhi")

    # -----------------------------
    # Build input DataFrame
    # -----------------------------
    X = pd.DataFrame([{
        "PM2.5": pm25,
        "PM10": pm10,
        "NO2": no2,
        "SO2": so2,
        "CO": co,
        "O3": o3,
        "year": year,
        "month": month,
        "day_of_week": day_of_week,
        "City": city
    }])

    st.divider()

    # -----------------------------
    # Prediction
    # -----------------------------
    if st.button("Predict AQI"):
        try:
            # Regression
            aqi_value = reg_model.predict(X)[0]

            # Classification
            aqi_bucket = cls_model.predict(X)[0]

            st.subheader("Prediction Results")
            st.metric("Predicted AQI", f"{aqi_value:.2f}")
            st.metric("AQI Category", aqi_bucket)

        except Exception as e:
            st.error("Prediction failed. Feature mismatch with training data.")
            st.code(str(e))