# -*- coding: utf-8 -*-
"""model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZkWywUjS203bQPcur_l2RzqfifV-E0d
"""

import streamlit as st


def calculate_aqi_pm25(pm25):
    if pm25 <= 12:
        return 50, "Good"
    elif pm25 <= 35.4:
        return 100, "Satisfactory"
    elif pm25 <= 55.4:
        return 200, "Moderate"
    elif pm25 <= 150.4:
        return 300, "Poor"
    elif pm25 <= 250.4:
        return 400, "Very Poor"
    else:
        return 500, "Severe"


def app():
    st.title("Simple AQI Prediction")

    st.write("This is a simple AQI prediction based only on PM2.5 value.")

    pm25 = st.number_input("Enter PM2.5 value (µg/m³)", value=50.0)

    if st.button("Predict AQI"):
        aqi, category = calculate_aqi_pm25(pm25)

        st.subheader("Prediction Result")
        st.metric("Estimated AQI", aqi)
        st.metric("AQI Category", category)

