# -*- coding: utf-8 -*-
"""multiapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L12RYQZa8zbaUPDGu4_IjIadL7l7RaF9
"""

import streamlit as st
class MultiApp:
    def __init__(self):
        self.apps = []

    def add_app(self, title, func):
        self.apps.append({
            "title": title,
            "function": func
        })

    def run(self):
        app = st.sidebar.radio(
            'Navigation ↩',
            self.apps,
            format_func=lambda app: app['title']
        )
        app['function']()