# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmUIW5rr6rMtiFYXWCZZPJA2PD4IiQG3
"""

import streamlit as st
from multiapp import MultiApp
import data_overview
import pre_processing
import eda
import model_building

app = MultiApp()

# Add all your application here
#app.add_app("Data page for demo", data.app)
app.add_app("Data Overview", data_overview.app)
app.add_app("Pre Processing", pre_processing.app)
app.add_app("Data Visualization", eda.app)
app.add_app("Model Building", model_building.app)

# The main app
app.run()